server:
  port: 7070

## Dubbo 服务提供者配置
#应用名
spring:
  dubbo:
    application:
      name: consumer
    #zookeeper的注册地址
    registry:
      address: zookeeper://127.0.0.1:2181
    #将消费者的控制层路径映射到dubbo中并由它管理
    scan: com.java.zd.controller
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
  #配置阿里巴巴数据源的四大件
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/good?useSSL=false&characterEncoding=utf8
    username: root
    password: root
    # 连接池的配置信息
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL